### ISSUE TITLE
Error message persists from login screen to sign up

### ISSUE THREAD

**Issue by sampocs** [ejshumaker/AdaptiveAlarm#61]
**Describe the bug**
If you try to log in with a poorly formatted email, it will correctly show the message "The email address is badly formatted". However, if you then move to the Sign Up page instead, the error message will still be showing.

**Severity**
Trivial

**To Reproduce**
1. Go to the sign in screen
2. Enter a poorly formatted email (i.e. testAccount)
3. Enter a password
4. Click Sign Up
5. Click Sign In

**Expected behavior**
I would expect that the error message disappears when you move to the Sign Up page.

**Smartphone:**
 - Device: iPhone 8

**Comment by tsteiner4** [comment]
@eschirtz Fixed this error by clearing errors when navigating between screens.
