### ISSUE TITLE
Home Page says "No Alarm Set" when alarms are set

### ISSUE THREAD

**Issue by kendarragh** [ejshumaker/AdaptiveAlarm#67]
**Describe the bug**
Home Page says "No Alarms Set" despite having alarms set
I have both manually set alarms and imported from my calendar. 
[Video link](https://streamable.com/d8cgz)

**To Reproduce**
[Video from fresh account](https://streamable.com/634x5)

**Expected behavior**
This was recorded on a Wednesday, so presumably it should show me my next alarm on Thursday morning

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.2

**Comment by ejshumaker** [comment]
Issue no longer occurring 04.30.2019.
