### ISSUE TITLE
Misleading error message when creating alarm with routine time of 0

### ISSUE THREAD

**Issue by kendarragh** [ejshumaker/AdaptiveAlarm#69]
**Describe the bug**
When creating an alarm with a routine time of zero, the user is told that the "Time to get ready must be a number!". Zero is a number, so this error is misleading. 

**To Reproduce**
1. Go to the screen to create an alarm
2. Set routine time to 0
3. Tap 'Save Alarm'

**Expected behavior**
I think this functionality should be allowed, for example when I want a reminder on when to leave the house but for something that I'd already be dressed and ready for. Either allow this functionality, or change the error message to tell the user that it must be a positive number. 

**Screenshots**
![Image 1](https://user-images.githubusercontent.com/16741112/56696802-88645780-66b2-11e9-89a6-89d95b1bf715.jpeg)
![Image 2](https://user-images.githubusercontent.com/16741112/56696801-87cbc100-66b2-11e9-9bac-16bb59d62c58.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.2

**Comment by ejshumaker** [comment]
Error message has been updated.
