### ISSUE TITLE
Alarm leaves no time for travel

### ISSUE THREAD

**Issue by connorstamper** [ejshumaker/AdaptiveAlarm#71]
The alarm does not take into account travel time when calculating wakeup time.

Severity: Blocker

1. Create a new alarm with 'Computer Sciences' as the destination
2. Add a routine time of 30 minutes and an arrival time of 8:30 am
3. Select any alarm sound and make the alarm for every day of the week
4. The calculated wakeup time will be 8:00 am on the home screen

Expected behavior
The alarm should show a time of before 8:00 am because of travel time

**Comment by tsteiner4** [comment]
Bug no longer exists after adjusting alarm time calculation. Closing issue.
