### ISSUE TITLE
Sign in button on sign up page is misleading

### ISSUE THREAD

**Issue by ashleybudden** [ejshumaker/AdaptiveAlarm#73]
**Describe the bug**
When creating an account, the sign in and sign up button are still available. As a user, I would expect sign in to sign me in with my newly created account. However, when that button is pressed, the user is redirected to the log in page with and the account was not created.

**To Reproduce**
1. Go to 'sign up'
2. Fill all field
3. Scroll down to sign in
4. notice the redirect to the sign in page, with no account created

**Expected behavior**
I would exepect it to either, create the account and redirect to the sign in page, sign them in automatically, or remove the button from the page.
**Screenshots**

**Smartphone (please complete the following information):**
iphone 6s plus

**Comment by tsteiner4** [comment]
Seems to be typical behavior on many applications. Sign in is with an existing account sign up is for a new account. You should be able to get back to the sign in page from the sign up page in case you realize you already have an account when you try to put in an email that already exists. Looking into changing the label to something more descriptive.
